# Generated by Django 6.0.3 on 2026-04-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
