# Generated by Django 6.0.5 on 2026-05-11 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_usersettings_ollama_host_usersettings_ollama_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, help_text='Weight in lbs', max_digits=6)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('import', 'Import'), ('device', 'Device')], default='manual', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weight Entry',
                'verbose_name_plural': 'Weight Entries',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['user', '-datetime'], name='dashboard_w_user_id_dee14d_idx')],
            },
        ),
    ]
