# Generated by Django 6.0.5 on 2026-05-11 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_weight_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('meal_name', models.CharField(blank=True, max_length=255)),
                ('foods_json', models.JSONField(default=list)),
                ('total_calories', models.IntegerField(default=0)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_carbs', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_fat', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('goal', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['-meal_date', 'meal_type'],
                'indexes': [models.Index(fields=['user', '-meal_date'], name='dashboard_m_user_id_1887b5_idx')],
            },
        ),
    ]
