# Generated by Django 6.0.5 on 2026-05-11 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_meal_plan_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('time_taken', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('calories', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Meal',
                'verbose_name_plural': 'User Meals',
                'ordering': ['-time_taken'],
                'indexes': [models.Index(fields=['user', '-time_taken'], name='dashboard_u_user_id_4d8610_idx')],
            },
        ),
    ]
