# Generated by Django 6.0.5 on 2026-05-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_meal_plan_start_end_dates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mealplan',
            new_name='dashboard_m_user_id_a32bd3_idx',
            old_name='dashboard_m_user_id_a1b2c3_idx',
        ),
    ]
