# Generated by Django 6.0.5 on 2026-05-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_mealplan_redesign'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mealentry',
            new_name='dashboard_m_meal_pl_e2c543_idx',
            old_name='dashboard_me_plan_day_idx',
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('mid_morning_snack', 'Mid-morning Snack'), ('lunch', 'Lunch'), ('evening_snack', 'Evening Snack'), ('dinner', 'Dinner'), ('post_workout', 'Post-workout'), ('bedtime_snack', 'Bedtime Snack')], max_length=20),
        ),
    ]
