# Generated by Django 6.0.5 on 2026-05-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_cleanup_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='weight_reminder_days',
            field=models.PositiveIntegerField(default=5, help_text='Notify after this many days without a weight log (0 = disabled)'),
        ),
    ]
