# Generated by Django 6.0.3 on 2026-04-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='subscription_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
